import Head from "next/head";
import NavLink from "../components/NavLink";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="p-4 bg-slate-800">
        <header className="flex items-center justify-between pb-2 mb-4 border-b-2 border-slate-500">
          <span className="text-2xl font-bold text-cyan-400">LOGO</span>
          <nav className="space-x-6">
            <NavLink href="/">Home</NavLink>
            <NavLink href="/movies">Movies</NavLink>
            <NavLink href="/products">Products</NavLink>
            <NavLink href="/about">About</NavLink>
          </nav>
        </header>

        <main className="text-white">{children}</main>

        <footer className="pt-2 mt-10 border-t-2 border-slate-500">
          <p className="text-base text-gray-400 ">This is Footer</p>
        </footer>
      </body>
    </html>
  );
}
